name: Lendo Continuous Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Firebase hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm clean-install
      - name: Vite build
        run: npm run build
      - name: Connect to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
